title: 杨强的blog
description: 记录技术思考与编码实践，偶尔聊点别的。
author: 杨强
email: york@example.com
lang: zh-CN
timezone: Asia/Shanghai
url: "https://yorksity.github.io"
baseurl: ""

permalink: /posts/:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - README.md
  - .github/